package com.kh.cntp.member.model.vo;

public class Member {
	
//	MEM_NO	NUMBER
//	MEM_ID	VARCHAR2(30 BYTE)
//	MEM_PWD	VARCHAR2(100 BYTE)
//	GENDER	CHAR(1 BYTE)
//	INGIDO	NUMBER
//	MEM_POINT	NUMBER
//	EMAIL	VARCHAR2(100 BYTE)
//	NICKNAME	VARCHAR2(30 BYTE)
//	MEM_NAME	VARCHAR2(10 BYTE)
//	MEM_AREA	VARCHAR2(10 BYTE)
//	PHONE	VARCHAR2(13 BYTE)
//	BIRTHDAY	DATE
//	DETAIL_AREA	VARCHAR2(30 BYTE)
//	MEM_STATUS	CHAR(1 BYTE)
//	ENROLL_DATE	DATE
//	GRADE	CHAR(1 BYTE)
	
	

}
